### ISSUE TITLE
Alternative ingredients must not allow alternatives

### ISSUE THREAD

**Issue by madhead** [madhead/recipes#11]
It's currently possible to have an unlimited level of alternatives for an ingredient:

```yml
ingredients:
  - name: Ingredient
    amount:
      quantity: 1
    alternatives:
      - name: Alternative ingredient
        amount:
          quantity: 1
        alternatives:
          - name: This ingredient must be disallowed
            amount:
              quantity: 1
              unit: tbsp.
```
