### ISSUE TITLE
Disallow unknown properties in amounts

### ISSUE THREAD

**Issue by madhead** [madhead/recipes#12]
```yml
amount:
  quantity:
    min: 3
    max: 4
    unknown: 5 # This property must not be allowed here
```
